version: 2

sources:
  - name: superstore
    database: SUPERSTORE_DATA
    schema: SUPERSTORE
    tables:
      - name: CUSTOMERS
        description: "Existing source table"
        columns:
          - name: CUSTOMER
            description: "Customer full name"
            meta:
              contains_pii: true
          - name: ID
            description: "Primary key"
          - name: CITY
          - name: MARKET
          - name: COUNTRY
          - name: REGION
          - name: SEGMENT
          - name: STATE
