# Reference this view as superstore__products
schema: SUPERSTORE
table_name: PRODUCTS

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  name:
    sql: '"NAME"'

  department:
    sql: '"DEPARTMENT"'

  category:
    sql: '"CATEGORY"'

measures:
  count:
    aggregate_type: count

#The info below was pulled from your dbt repository and is read-only.
dbt:
  name: products
  target_schema: SUPERSTORE
  config:
    materialized: view
  code: |-
    {{ config(materialized='view') }}

    select *
    from {{ source('superstore', 'PRODUCTS') }}
