name: superstore_metadata_only
version: 1.0.0
config-version: 2
profile: default
model-paths: ["models"]
target-path: "target"

models:
  superstore_metadata_only:
    +materialized: view
    +schema: SUPERSTORE_DATA_ANALYTICS