version: 2
sources:
  - name: superstore
    database: SUPERSTORE_DATA
    schema: SUPERSTORE
    tables:
      - name: CUSTOMERS
        columns:
          - name: CUSTOMER
            meta:
              contains_pii: true
          - name: ID
          - name: CITY
          - name: MARKET
          - name: COUNTRY
          - name: REGION
          - name: SEGMENT
          - name: STATE
      - name: ORDERS
      - name: PEOPLE
      - name: PRODUCTS
      - name: RETURNS
      - name: SALES
