version: 2
sources:
  - name: superstore
    database: SUPERSTORE_DATA
    schema: SUPERSTORE
    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: PEOPLE
      - name: PRODUCTS
      - name: RETURNS