sources:
  - name: SUPERSTORE
    database: SUPERSTORE_DATA
    schema: SUPERSTORE          # raw tables live here
    tables:
      - name: CUSTOMERS
        columns:
          - name: CUSTOMER
            meta: { contains_pii: true }
      - name: ORDERS
      - name: PEOPLE
      - name: PRODUCTS
      - name: RETURNS
      - name: SALES